AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

# This is only relevant for 1.9, which I don't care that much about.
Style/Encoding:
  Enabled: false

# VT100 is too oldschool, even for me.
Style/LineLength:
  Max: 100

# Hubris, one of the Three Great Virtues
# http://c2.com/cgi/wiki?LazinessImpatienceHubris
Rails/HasAndBelongsToMany:
  Enabled: false

